id: I3F5B1F44
legacy_id: P009297
ocr_import_info:
  bdrc_scan_id: W8LS17286
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T09:13:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:45:41.011433+00:00'
last_modified: 2022-09-04 11:46:30.992966
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17286
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17286
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཅན་ཚ་མགུར་དགོན་གྱི་ཁ་འདོན་དང་ཆོ་ག་ཕྱོགས་བསྒྲིགས།
statistics:
  ocr_word_mean_confidence_index: 0.6407195638368313
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I8LS17302:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17302
      total_pages: 2164
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17302.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6407195638368313
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
