id: P009297
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:32:07.999689
source_metadata:
  id: bdr:W8LS17286
  title: གཅན་ཚ་མགུར་དགོན་གྱི་ཁ་འདོན་དང་ཆོ་ག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    df90892332d14ad5864bb8c32d93d667:
      image_group_id: I8LS17302
      title: ''
      volume_number: 1
      total_pages: 2164
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
