id: P009297
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17286
  title: གཅན་ཚ་མགུར་དགོན་གྱི་ཁ་འདོན་དང་ཆོ་ག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    df90892332d14ad5864bb8c32d93d667:
      image_group_id: I8LS17302
      title: ''
      volume_number: 1
      total_pages: 2164
      base_file: v001.txt
